'use client';

/**
 * Accessible text summary of a route (§16.11, §3.6, §4.4).
 *
 * Every route must be understandable without looking at the map. This component
 * is that text, and it is also where §3.6's four obligations are discharged
 * together: why this route was selected, what data was used, what remains
 * unknown, and which constraints could not be met.
 *
 * The order is deliberate. Unknowns and unmet constraints come *before* the
 * metrics, because a distance and an ascent figure read as authoritative and a
 * caveat placed after them arrives too late to change how they are read.
 */

export type Verdict =
  | 'fully_satisfied'
  | 'satisfied_with_unknown_data'
  | 'partially_satisfied'
  | 'not_feasible';

export interface Violation {
  constraintKey: string;
  statedAs?: string | null;
  requested?: number | string | null;
  observed?: number | string | null;
  distanceM?: number;
  detail?: string;
}

export interface RouteSummaryProps {
  name: string;
  originKind: 'official' | 'community' | 'imported' | 'private' | 'generated';
  selectionReason?: string;
  distanceM: number;
  ascentM: number | null;
  descentM: number | null;
  maxGradePercent: number | null;
  gradientWindowM?: number | null;
  surfaceCompositionM: Record<string, number>;
  verdict: Verdict;
  violations?: readonly Violation[];
  unevaluated?: readonly { key: string; detail: string }[];
  standingLimitations?: readonly { check: string; detail: string }[];
  sources: readonly { name: string; licence: string; lastImport?: string | null }[];
  geometryVersion?: string;
}

const VERDICT_TEXT: Record<Verdict, string> = {
  fully_satisfied:
    'Every requirement was checked against available data and met.',
  satisfied_with_unknown_data:
    'No requirement was found to be broken, but some could not be checked because the data does not exist.',
  partially_satisfied: 'This route does not meet every requirement you set.',
  not_feasible:
    'Contour could not find a route meeting every requirement. This is the closest it found.',
};

function formatKm(metres: number): string {
  return `${(metres / 1000).toFixed(1)} km`;
}

export function RouteSummary(props: RouteSummaryProps) {
  const {
    name,
    originKind,
    selectionReason,
    distanceM,
    ascentM,
    descentM,
    maxGradePercent,
    gradientWindowM,
    surfaceCompositionM,
    verdict,
    violations = [],
    unevaluated = [],
    standingLimitations = [],
    sources,
    geometryVersion,
  } = props;

  const unknownSurfaceM = surfaceCompositionM.unknown ?? 0;
  const unknownShare = distanceM > 0 ? Math.round((unknownSurfaceM / distanceM) * 100) : 0;

  return (
    <section className="route-summary" aria-label={`Summary of ${name}`}>
      <header>
        <h2>{name}</h2>
        <p className="route-summary__origin">
          {originKind === 'generated'
            ? 'Generated by Contour using the routing engine and the sources listed below. This is not an official route.'
            : originKind === 'official'
              ? 'From an official published dataset.'
              : originKind === 'imported'
                ? 'Imported from a file you uploaded.'
                : originKind === 'community'
                  ? 'Published by another Contour user.'
                  : 'Your private route.'}
        </p>
      </header>

      <p className="route-summary__verdict" data-verdict={verdict}>
        {VERDICT_TEXT[verdict]}
      </p>

      {violations.length > 0 ? (
        <section aria-label="Requirements not met">
          <h3>What this route does not meet</h3>
          <ul>
            {violations.map((violation) => (
              <li key={violation.constraintKey}>
                <strong>{violation.statedAs ?? violation.constraintKey.replace(/_/g, ' ')}</strong>
                {violation.detail ? `: ${violation.detail}` : null}
                {violation.distanceM ? ` (${formatKm(violation.distanceM)} affected)` : null}
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {unevaluated.length > 0 ? (
        <section aria-label="What could not be checked">
          <h3>What could not be checked</h3>
          <ul>
            {unevaluated.map((item) => (
              <li key={item.key}>{item.detail}</li>
            ))}
          </ul>
        </section>
      ) : null}

      <section aria-label="Route figures">
        <h3>Figures</h3>
        <dl className="route-summary__figures">
          <div>
            <dt>Distance</dt>
            <dd>{formatKm(distanceM)}</dd>
          </div>
          <div>
            <dt>Ascent</dt>
            <dd>{ascentM == null ? 'Unknown — no elevation data' : `${Math.round(ascentM)} m`}</dd>
          </div>
          <div>
            <dt>Descent</dt>
            <dd>
              {descentM == null ? 'Unknown — no elevation data' : `${Math.round(descentM)} m`}
            </dd>
          </div>
          <div>
            <dt>Steepest gradient</dt>
            <dd>
              {maxGradePercent == null
                ? 'Unknown'
                : `${maxGradePercent.toFixed(1)}%${
                    gradientWindowM ? ` measured over ${gradientWindowM} m` : ''
                  }`}
            </dd>
          </div>
          <div>
            <dt>Surface not recorded</dt>
            <dd>
              {formatKm(unknownSurfaceM)} ({unknownShare}% of the route)
            </dd>
          </div>
        </dl>
      </section>

      {selectionReason ? (
        <section aria-label="Why this route">
          <h3>Why this route</h3>
          <p>{selectionReason}</p>
        </section>
      ) : null}

      <section aria-label="Sources and licences">
        <h3>Sources</h3>
        <ul className="route-summary__sources">
          {sources.map((source) => (
            <li key={source.name}>
              {source.name} — {source.licence}
              {source.lastImport ? ` · imported ${source.lastImport}` : ' · never imported'}
            </li>
          ))}
        </ul>
        {geometryVersion ? (
          <p className="route-summary__version">Geometry version {geometryVersion}</p>
        ) : null}
      </section>

      {standingLimitations.length > 0 ? (
        <section aria-label="What Contour cannot check at all">
          <h3>What Contour cannot check</h3>
          <p>
            These are limitations of this Contour deployment rather than gaps in this
            route&rsquo;s data.
          </p>
          <ul>
            {standingLimitations.map((limitation) => (
              <li key={limitation.check}>{limitation.detail}</li>
            ))}
          </ul>
        </section>
      ) : null}

      <p className="route-summary__disclaimer">
        Contour reports observable, sourced attributes. It does not assess whether a
        route is safe, and no figure here should be read as a safety judgement.
      </p>
    </section>
  );
}
