"""Widen route_source.access_method and persist registry notes

Revision ID: 273989e4aad8
Revises: e8339eb64415
Create Date: 2026-07-27 06:53:02.038501
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '273989e4aad8'
down_revision: str | None = 'e8339eb64415'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_source', sa.Column('notes', sa.Text(), nullable=True))
    op.alter_column('route_source', 'access_method',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('route_source', 'access_method',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
    op.drop_column('route_source', 'notes')
    # ### end Alembic commands ###
