"""initial schema

Revision ID: 47a3e7324555
Revises: 
Create Date: 2026-07-26 18:27:34.519814
"""
from __future__ import annotations

from collections.abc import Sequence

import geoalchemy2
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '47a3e7324555'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organisation')),
    sa.UniqueConstraint('slug', name=op.f('uq_organisation_slug'))
    )
    op.create_table('source_licence',
    sa.Column('identifier', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('redistribution', sa.Enum('PERMITTED', 'PERMITTED_WITH_ATTRIBUTION', 'PERMITTED_SHARE_ALIKE', 'NON_COMMERCIAL_ONLY', 'PROHIBITED', 'UNKNOWN', name='redistribution_permission'), nullable=False),
    sa.Column('commercial_use_permitted', sa.Boolean(), nullable=True),
    sa.Column('derivative_works_permitted', sa.Boolean(), nullable=True),
    sa.Column('share_alike_required', sa.Boolean(), nullable=True),
    sa.Column('attribution_required', sa.Boolean(), nullable=True),
    sa.Column('restriction_summary', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_method', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_licence')),
    sa.UniqueConstraint('identifier', name=op.f('uq_source_licence_identifier'))
    )
    op.create_table('app_user',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('email_normalised', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_operator', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_app_user_organisation_id_organisation'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email_normalised', name='uq_app_user_email')
    )
    op.create_index('ix_app_user_organisation', 'app_user', ['organisation_id'], unique=False)
    op.create_table('route_source',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('documentation_url', sa.Text(), nullable=True),
    sa.Column('documentation_evidence', sa.Text(), nullable=True),
    sa.Column('access_method', sa.String(length=120), nullable=True),
    sa.Column('access_url', sa.Text(), nullable=True),
    sa.Column('authentication_method', sa.String(length=120), nullable=True),
    sa.Column('licence_id', sa.UUID(), nullable=True),
    sa.Column('permitted_uses', sa.Text(), nullable=True),
    sa.Column('redistribution_restrictions', sa.Text(), nullable=True),
    sa.Column('coverage_description', sa.Text(), nullable=True),
    sa.Column('coverage_area', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('route_types', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('available_attributes', postgresql.ARRAY(sa.String(length=60)), nullable=False),
    sa.Column('update_method', sa.Text(), nullable=True),
    sa.Column('last_source_update', sa.Date(), nullable=True),
    sa.Column('last_successful_import', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_verification_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('staleness_threshold_days', sa.Integer(), nullable=True),
    sa.Column('known_quality_limitations', sa.Text(), nullable=True),
    sa.Column('connector_status', sa.Enum('ACTIVE', 'DEGRADED', 'FAILING', 'STALE', 'AWAITING_CREDENTIALS', 'AWAITING_APPROVAL', 'IMPLEMENTED_BLOCKED_EGRESS', 'NOT_IMPLEMENTED', 'DISABLED', name='connector_status'), nullable=False),
    sa.Column('connector_key', sa.String(length=120), nullable=True),
    sa.Column('failure_status', sa.Text(), nullable=True),
    sa.Column('failure_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('contact_requirement', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['licence_id'], ['source_licence.id'], name=op.f('fk_route_source_licence_id_source_licence'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_source')),
    sa.UniqueConstraint('slug', name='uq_route_source_slug')
    )
    op.create_index('ix_route_source_connector_status', 'route_source', ['connector_status'], unique=False)
    op.create_table('connected_account',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('external_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.LargeBinary(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_scopes', sa.Text(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_connected_account_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_account')),
    sa.UniqueConstraint('user_id', 'provider', name='uq_connected_account_provider')
    )
    op.create_table('journey_project',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('constraints', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_example_plan', sa.Boolean(), nullable=False),
    sa.Column('example_plan_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_journey_project_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_journey_project')),
    sa.UniqueConstraint('slug', name=op.f('uq_journey_project_slug'))
    )
    op.create_index('ix_journey_project_owner', 'journey_project', ['owner_user_id'], unique=False)
    op.create_table('source_attribution',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('required_surfaces', postgresql.ARRAY(sa.String(length=40)), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_source_attribution_source_id_route_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_attribution'))
    )
    op.create_table('source_import',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('job_id', sa.String(length=120), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('stages_completed', sa.Integer(), nullable=False),
    sa.Column('stages_total', sa.Integer(), nullable=True),
    sa.Column('records_seen', sa.Integer(), nullable=False),
    sa.Column('records_written', sa.Integer(), nullable=False),
    sa.Column('records_rejected', sa.Integer(), nullable=False),
    sa.Column('request_url', sa.Text(), nullable=True),
    sa.Column('response_checksum', sa.String(length=128), nullable=True),
    sa.Column('licence_snapshot_id', sa.UUID(), nullable=True),
    sa.Column('attribution_snapshot', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('transformation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['licence_snapshot_id'], ['source_licence.id'], name=op.f('fk_source_import_licence_snapshot_id_source_licence'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_source_import_source_id_route_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_import')),
    sa.UniqueConstraint('idempotency_key', name='uq_source_import_idempotency_key')
    )
    op.create_index('ix_source_import_source_started', 'source_import', ['source_id', 'started_at'], unique=False)
    op.create_table('route',
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('origin_kind', sa.Enum('OFFICIAL', 'COMMUNITY', 'IMPORTED', 'PRIVATE', 'GENERATED', name='route_origin_kind'), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'UNLISTED', 'PUBLIC', 'ARCHIVED', name='route_visibility'), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('organisation_id', sa.UUID(), nullable=True),
    sa.Column('journey_project_id', sa.UUID(), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('country_codes', postgresql.ARRAY(sa.String(length=2)), nullable=False),
    sa.Column('region_names', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('network_names', postgresql.ARRAY(sa.String(length=120)), nullable=False),
    sa.Column('redistribution_blocked', sa.Boolean(), nullable=False),
    sa.Column('redistribution_block_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['current_version_id'], ['route_version.id'], name=op.f('fk_route_current_version_id_route_version'), ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['journey_project_id'], ['journey_project.id'], name=op.f('fk_route_journey_project_id_journey_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], name=op.f('fk_route_organisation_id_organisation'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_route_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route'))
    )
    op.create_index('ix_route_origin_kind', 'route', ['origin_kind'], unique=False)
    op.create_index('ix_route_owner_visibility', 'route', ['owner_user_id', 'visibility'], unique=False)
    op.create_table('route_intent',
    sa.Column('schema_version', sa.Integer(), nullable=False),
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('journey_project_id', sa.UUID(), nullable=True),
    sa.Column('request_text', sa.Text(), nullable=True),
    sa.Column('parser', sa.String(length=40), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=True),
    sa.Column('parse_trace', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unresolved_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confirmed_by_user', sa.Boolean(), nullable=False),
    sa.Column('origin_text', sa.String(length=500), nullable=True),
    sa.Column('origin_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('destination_text', sa.String(length=500), nullable=True),
    sa.Column('destination_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('via_points', geoalchemy2.types.Geometry(geometry_type='MULTIPOINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('via_texts', postgresql.ARRAY(sa.String(length=500)), nullable=False),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('bicycle_type', sa.Enum('ROAD', 'HYBRID', 'CROSS', 'MOUNTAIN', 'EBIKE', 'CUSTOM', name='bicycle_type'), nullable=True),
    sa.Column('surface_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('max_total_distance_m', sa.Float(), nullable=True),
    sa.Column('max_daily_distance_m', sa.Float(), nullable=True),
    sa.Column('max_daily_riding_time_s', sa.Integer(), nullable=True),
    sa.Column('max_daily_ascent_m', sa.Float(), nullable=True),
    sa.Column('max_gradient_percent', sa.Float(), nullable=True),
    sa.Column('preferred_gradient_percent', sa.Float(), nullable=True),
    sa.Column('number_of_days', sa.Integer(), nullable=True),
    sa.Column('fixed_overnight_stops', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('flexible_overnight_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_pois', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avoided_roads', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('avoided_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ferry_preference', sa.String(length=30), nullable=True),
    sa.Column('scenic_preference', sa.String(length=30), nullable=True),
    sa.Column('coast_proximity_m', sa.Float(), nullable=True),
    sa.Column('cycle_infrastructure_preference', sa.String(length=30), nullable=True),
    sa.Column('unknown_data_tolerance_ratio', sa.Float(), nullable=True),
    sa.Column('export_target', sa.String(length=40), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_project_id'], ['journey_project.id'], name=op.f('fk_route_intent_journey_project_id_journey_project'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_route_intent_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_intent'))
    )
    op.create_index('ix_route_intent_owner', 'route_intent', ['owner_user_id'], unique=False)
    op.create_table('avoid_area',
    sa.Column('owner_user_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('hard', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_avoid_area_owner_user_id_app_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_avoid_area_route_id_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_avoid_area'))
    )
    op.create_index('ix_avoid_area_owner', 'avoid_area', ['owner_user_id'], unique=False)
    op.create_table('import_job',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('detected_format', sa.String(length=20), nullable=True),
    sa.Column('declared_content_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=False),
    sa.Column('stored_uri', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage', sa.String(length=80), nullable=True),
    sa.Column('stages_completed', sa.Integer(), nullable=False),
    sa.Column('stages_total', sa.Integer(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('map_matched', sa.Boolean(), nullable=False),
    sa.Column('match_deviation_max_m', sa.Float(), nullable=True),
    sa.Column('kept_geometry', sa.String(length=20), nullable=True),
    sa.Column('validation_report', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_import_job_route_id_route'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_import_job_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_job')),
    sa.UniqueConstraint('idempotency_key', name='uq_import_job_idempotency_key')
    )
    op.create_index('ix_import_job_user', 'import_job', ['user_id'], unique=False)
    op.create_table('route_constraint',
    sa.Column('intent_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('hard', sa.Boolean(), nullable=False),
    sa.Column('predicate', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('stated_as', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['route_intent.id'], name=op.f('fk_route_constraint_intent_id_route_intent'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_constraint'))
    )
    op.create_index('ix_route_constraint_intent', 'route_constraint', ['intent_id'], unique=False)
    op.create_table('route_source_version',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('import_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('source_checksum', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('published_description', sa.Text(), nullable=True),
    sa.Column('published_date', sa.Date(), nullable=True),
    sa.Column('development_status', sa.String(length=120), nullable=True),
    sa.Column('geom_original', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_normalised', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_matched', geoalchemy2.types.Geometry(geometry_type='MULTILINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('match_deviation_max_m', sa.Float(), nullable=True),
    sa.Column('match_deviation_mean_m', sa.Float(), nullable=True),
    sa.Column('raw_payload_uri', sa.Text(), nullable=True),
    sa.Column('raw_payload_withheld_reason', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('transformation_log', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['source_import.id'], name=op.f('fk_route_source_version_import_id_source_import'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_route_source_version_route_id_route'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_route_source_version_source_id_route_source'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_source_version')),
    sa.UniqueConstraint('source_id', 'source_record_id', 'source_checksum', name='uq_route_source_version_identity')
    )
    op.create_index('ix_route_source_version_source', 'route_source_version', ['source_id'], unique=False)
    op.create_table('route_version',
    sa.Column('route_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_version_id', sa.UUID(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('change_kind', sa.String(length=40), nullable=False),
    sa.Column('change_summary', sa.Text(), nullable=True),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('geom_generated', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_original', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom_matched', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('descent_m', sa.Float(), nullable=True),
    sa.Column('min_elevation_m', sa.Float(), nullable=True),
    sa.Column('max_elevation_m', sa.Float(), nullable=True),
    sa.Column('net_elevation_change_m', sa.Float(), nullable=True),
    sa.Column('elevation_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('elevation_gap_m', sa.Float(), nullable=True),
    sa.Column('max_grade_percent', sa.Float(), nullable=True),
    sa.Column('sustained_grade_percent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('surface_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cycle_infrastructure_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('road_class_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ferry_distance_m', sa.Float(), nullable=True),
    sa.Column('ferry_crossing_count', sa.Integer(), nullable=True),
    sa.Column('bicycle_type', sa.Enum('ROAD', 'HYBRID', 'CROSS', 'MOUNTAIN', 'EBIKE', 'CUSTOM', name='bicycle_type'), nullable=True),
    sa.Column('routing_provider', sa.String(length=60), nullable=True),
    sa.Column('routing_engine_version', sa.String(length=60), nullable=True),
    sa.Column('routing_tile_version', sa.String(length=120), nullable=True),
    sa.Column('elevation_provider', sa.String(length=60), nullable=True),
    sa.Column('elevation_dataset_id', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('version_number > 0', name=op.f('ck_route_version_version_number_positive')),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['app_user.id'], name=op.f('fk_route_version_created_by_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_version_id'], ['route_version.id'], name=op.f('fk_route_version_parent_version_id_route_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_route_version_route_id_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_version')),
    sa.UniqueConstraint('route_id', 'version_number', name='uq_route_version_number')
    )
    op.create_index('ix_route_version_route', 'route_version', ['route_id'], unique=False)
    op.create_table('elevation_sample',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('elevation_m', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('dataset_id', sa.String(length=200), nullable=True),
    sa.Column('source_resolution_m', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_elevation_sample_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_elevation_sample')),
    sa.UniqueConstraint('route_version_id', 'sequence', name='uq_elevation_sample_sequence')
    )
    op.create_index('ix_elevation_sample_version', 'elevation_sample', ['route_version_id'], unique=False)
    op.create_table('point_of_interest',
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('published_description', sa.Text(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opening_hours_raw', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_point_of_interest_source_id_route_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['route_source_version.id'], name=op.f('fk_point_of_interest_source_version_id_route_source_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_point_of_interest')),
    sa.UniqueConstraint('source_id', 'source_record_id', name='uq_poi_source_record')
    )
    op.create_index('ix_poi_geom_category', 'point_of_interest', ['category'], unique=False)
    op.create_table('route_score',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('profile_key', sa.String(length=120), nullable=False),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unscored_components', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('method_version', sa.String(length=40), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_route_score_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_score')),
    sa.UniqueConstraint('route_version_id', 'profile_key', name='uq_route_score_profile')
    )
    op.create_table('route_segment',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('start_distance_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('graph_edge_id', sa.String(length=80), nullable=True),
    sa.Column('osm_way_id', sa.Integer(), nullable=True),
    sa.Column('surface_tag_raw', sa.String(length=80), nullable=True),
    sa.Column('surface_generalised', sa.Enum('PAVED_SMOOTH', 'PAVED', 'PAVED_ROUGH', 'COMPACTED', 'DIRT', 'GRAVEL', 'PATH', 'IMPASSABLE', name='generalised_surface'), nullable=True),
    sa.Column('surface_family', sa.Enum('PAVED', 'UNPAVED', 'UNKNOWN', name='surface_family'), nullable=False),
    sa.Column('surface_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('smoothness_tag_raw', sa.String(length=80), nullable=True),
    sa.Column('tracktype_tag_raw', sa.String(length=40), nullable=True),
    sa.Column('bicycle_access', sa.Enum('YES', 'NO', 'DESIGNATED', 'PERMISSIVE', 'DESTINATION', 'PRIVATE', 'CUSTOMERS', 'DISMOUNT', 'UNKNOWN', name='bicycle_access'), nullable=False),
    sa.Column('bicycle_access_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('oneway_bicycle', sa.Boolean(), nullable=True),
    sa.Column('access_conditional_raw', sa.Text(), nullable=True),
    sa.Column('seasonal_access_raw', sa.Text(), nullable=True),
    sa.Column('cycle_lane', sa.Enum('ABSENT', 'SHARED', 'DEDICATED', 'SEPARATED', name='cycle_lane_kind'), nullable=True),
    sa.Column('cycle_lane_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('road_class', sa.Enum('MOTORWAY', 'TRUNK', 'PRIMARY', 'SECONDARY', 'TERTIARY', 'UNCLASSIFIED', 'RESIDENTIAL', 'SERVICE', 'LIVING_STREET', 'TRACK', 'PATH', 'CYCLEWAY', 'FOOTWAY', 'BRIDLEWAY', 'STEPS', 'FERRY', 'UNKNOWN', name='road_class'), nullable=False),
    sa.Column('road_class_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('speed_limit_kph', sa.Integer(), nullable=True),
    sa.Column('speed_limit_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('width_m', sa.Float(), nullable=True),
    sa.Column('lit', sa.Boolean(), nullable=True),
    sa.Column('shoulder', sa.Boolean(), nullable=True),
    sa.Column('is_bridge', sa.Boolean(), nullable=True),
    sa.Column('is_tunnel', sa.Boolean(), nullable=True),
    sa.Column('is_ferry', sa.Boolean(), nullable=True),
    sa.Column('is_ford', sa.Boolean(), nullable=True),
    sa.Column('has_steps', sa.Boolean(), nullable=True),
    sa.Column('barrier_raw', sa.String(length=80), nullable=True),
    sa.Column('construction_status_raw', sa.String(length=80), nullable=True),
    sa.Column('grade_percent', sa.Float(), nullable=True),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('descent_m', sa.Float(), nullable=True),
    sa.Column('elevation_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('last_import_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('distance_m >= 0', name=op.f('ck_route_segment_distance_non_negative')),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_route_segment_route_version_id_route_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_route_segment_source_id_route_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_segment')),
    sa.UniqueConstraint('route_version_id', 'sequence', name='uq_route_segment_sequence')
    )
    op.create_index('ix_route_segment_version', 'route_segment', ['route_version_id'], unique=False)
    op.create_table('route_variant',
    sa.Column('comparison_key', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('shared_distance_m', sa.Float(), nullable=True),
    sa.Column('unique_distance_m', sa.Float(), nullable=True),
    sa.Column('corridor_max_deviation_m', sa.Float(), nullable=True),
    sa.Column('corridor_mean_deviation_m', sa.Float(), nullable=True),
    sa.Column('detour_ratio', sa.Float(), nullable=True),
    sa.Column('overlap_with', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_route_variant_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_route_variant')),
    sa.UniqueConstraint('comparison_key', 'slug', name='uq_route_variant_slug')
    )
    op.create_index('ix_route_variant_comparison', 'route_variant', ['comparison_key'], unique=False)
    op.create_table('source_discrepancy',
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('left_version_id', sa.UUID(), nullable=False),
    sa.Column('right_version_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('attribute_key', sa.String(length=80), nullable=True),
    sa.Column('left_value', sa.Text(), nullable=True),
    sa.Column('right_value', sa.Text(), nullable=True),
    sa.Column('max_separation_m', sa.Float(), nullable=True),
    sa.Column('overlap_ratio', sa.Float(), nullable=True),
    sa.Column('length_difference_m', sa.Float(), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolution_used_version_id', sa.UUID(), nullable=True),
    sa.Column('resolution_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('left_version_id <> right_version_id', name=op.f('ck_source_discrepancy_different_versions')),
    sa.ForeignKeyConstraint(['left_version_id'], ['route_source_version.id'], name=op.f('fk_source_discrepancy_left_version_id_route_source_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolution_used_version_id'], ['route_source_version.id'], name=op.f('fk_source_discrepancy_resolution_used_version_id_route_source_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['right_version_id'], ['route_source_version.id'], name=op.f('fk_source_discrepancy_right_version_id_route_source_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_source_discrepancy_route_id_route'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_discrepancy'))
    )
    op.create_index('ix_source_discrepancy_route', 'source_discrepancy', ['route_id'], unique=False)
    op.create_table('stage',
    sa.Column('journey_project_id', sa.UUID(), nullable=False),
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('planned_date', sa.Date(), nullable=True),
    sa.Column('is_rest_day', sa.Boolean(), nullable=False),
    sa.Column('start_distance_m', sa.Float(), nullable=False),
    sa.Column('end_distance_m', sa.Float(), nullable=False),
    sa.Column('distance_m', sa.Float(), nullable=False),
    sa.Column('ascent_m', sa.Float(), nullable=True),
    sa.Column('descent_m', sa.Float(), nullable=True),
    sa.Column('max_grade_percent', sa.Float(), nullable=True),
    sa.Column('elevation_status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('start_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('end_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('end_locked', sa.Boolean(), nullable=False),
    sa.Column('selection_reason', sa.Text(), nullable=True),
    sa.Column('balance_strategy', sa.Enum('DISTANCE', 'ASCENT', 'TIME', 'WEIGHTED', name='stage_balance_strategy'), nullable=True),
    sa.Column('constraint_violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unknown_services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['journey_project_id'], ['journey_project.id'], name=op.f('fk_stage_journey_project_id_journey_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_stage_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stage')),
    sa.UniqueConstraint('route_version_id', 'sequence', name='uq_stage_sequence')
    )
    op.create_index('ix_stage_project', 'stage', ['journey_project_id'], unique=False)
    op.create_table('validation_result',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('intent_id', sa.UUID(), nullable=True),
    sa.Column('verdict', sa.Enum('FULLY_SATISFIED', 'SATISFIED_WITH_UNKNOWN_DATA', 'PARTIALLY_SATISFIED', 'NOT_FEASIBLE', name='feasibility_verdict'), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('violations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('unevaluated', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('resolve_attempts', sa.Integer(), nullable=False),
    sa.Column('exhausted_attempts', sa.Boolean(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['intent_id'], ['route_intent.id'], name=op.f('fk_validation_result_intent_id_route_intent'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_validation_result_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_result'))
    )
    op.create_index('ix_validation_result_version', 'validation_result', ['route_version_id'], unique=False)
    op.create_table('waypoint',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('snapped_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('snap_distance_m', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_waypoint_route_version_id_route_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_waypoint')),
    sa.UniqueConstraint('route_version_id', 'sequence', name='uq_waypoint_sequence')
    )
    op.create_index('ix_waypoint_version', 'waypoint', ['route_version_id'], unique=False)
    op.create_table('bicycle_route_membership',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('network', sa.String(length=40), nullable=True),
    sa.Column('route_ref', sa.String(length=120), nullable=True),
    sa.Column('route_name', sa.String(length=500), nullable=True),
    sa.Column('operator', sa.String(length=255), nullable=True),
    sa.Column('relation_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segment.id'], name=op.f('fk_bicycle_route_membership_segment_id_route_segment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_bicycle_route_membership_source_id_route_source'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bicycle_route_membership'))
    )
    op.create_index('ix_bicycle_route_membership_ref', 'bicycle_route_membership', ['network', 'route_ref'], unique=False)
    op.create_index('ix_bicycle_route_membership_segment', 'bicycle_route_membership', ['segment_id'], unique=False)
    op.create_table('climb',
    sa.Column('route_version_id', sa.UUID(), nullable=False),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('start_distance_m', sa.Float(), nullable=False),
    sa.Column('end_distance_m', sa.Float(), nullable=False),
    sa.Column('length_m', sa.Float(), nullable=False),
    sa.Column('elevation_gain_m', sa.Float(), nullable=False),
    sa.Column('start_elevation_m', sa.Float(), nullable=True),
    sa.Column('end_elevation_m', sa.Float(), nullable=True),
    sa.Column('start_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('end_geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('average_grade_percent', sa.Float(), nullable=False),
    sa.Column('max_grade_percent', sa.Float(), nullable=True),
    sa.Column('max_sustained_grade_percent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gradient_distribution_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('surface_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cycle_infrastructure_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('road_class_composition_m', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('elevation_gap_m', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detection_parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('end_distance_m > start_distance_m', name=op.f('ck_climb_climb_length_positive')),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_climb_route_version_id_route_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_climb_stage_id_stage'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_climb'))
    )
    op.create_index('ix_climb_version', 'climb', ['route_version_id'], unique=False)
    op.create_table('export_job',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('route_version_id', sa.UUID(), nullable=True),
    sa.Column('stage_id', sa.UUID(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('scope', sa.String(length=30), nullable=False),
    sa.Column('selection_start_m', sa.Float(), nullable=True),
    sa.Column('selection_end_m', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('stage_name', sa.String(length=80), nullable=True),
    sa.Column('stages_completed', sa.Integer(), nullable=False),
    sa.Column('stages_total', sa.Integer(), nullable=True),
    sa.Column('output_uri', sa.Text(), nullable=True),
    sa.Column('output_checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('attribution_manifest', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocked_by_licence', sa.Boolean(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_version_id'], ['route_version.id'], name=op.f('fk_export_job_route_version_id_route_version'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stage_id'], ['stage.id'], name=op.f('fk_export_job_stage_id_stage'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_export_job_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_export_job')),
    sa.UniqueConstraint('idempotency_key', name='uq_export_job_idempotency_key')
    )
    op.create_index('ix_export_job_user', 'export_job', ['user_id'], unique=False)
    op.create_table('segment_attribute',
    sa.Column('segment_id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value_raw', sa.Text(), nullable=True),
    sa.Column('value_normalised', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('KNOWN', 'UNKNOWN', 'NOT_APPLICABLE', 'CONFLICTING', name='knowledge_status'), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('source_version_id', sa.UUID(), nullable=True),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segment.id'], name=op.f('fk_segment_attribute_segment_id_route_segment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['route_source.id'], name=op.f('fk_segment_attribute_source_id_route_source'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_version_id'], ['route_source_version.id'], name=op.f('fk_segment_attribute_source_version_id_route_source_version'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_segment_attribute')),
    sa.UniqueConstraint('segment_id', 'key', 'source_id', name='uq_segment_attribute_key')
    )
    op.create_index('ix_segment_attribute_key', 'segment_attribute', ['key'], unique=False)
    op.create_index('ix_segment_attribute_segment', 'segment_attribute', ['segment_id'], unique=False)
    op.create_table('user_report',
    sa.Column('reporter_user_id', sa.UUID(), nullable=True),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('segment_id', sa.UUID(), nullable=True),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('operator_note', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['app_user.id'], name=op.f('fk_user_report_reporter_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['route.id'], name=op.f('fk_user_report_route_id_route'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['route_segment.id'], name=op.f('fk_user_report_segment_id_route_segment'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_report'))
    )
    op.create_index('ix_user_report_route', 'user_report', ['route_id'], unique=False)
    # ### end Alembic commands ###

    # route.current_version_id and route_version.route_id reference each other,
    # so the constraint cannot be created inline with either table. SQLAlchemy
    # marks it use_alter=True, which autogenerate does not emit; without this it
    # is silently missing from the database and `alembic check` fails.
    op.create_foreign_key(
        op.f("fk_route_current_version_id_route_version"),
        "route",
        "route_version",
        ["current_version_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_route_current_version_id_route_version"), "route", type_="foreignkey"
    )
    op.drop_index('ix_user_report_route', table_name='user_report')
    op.drop_table('user_report')
    op.drop_index('ix_segment_attribute_segment', table_name='segment_attribute')
    op.drop_index('ix_segment_attribute_key', table_name='segment_attribute')
    op.drop_table('segment_attribute')
    op.drop_index('ix_export_job_user', table_name='export_job')
    op.drop_table('export_job')
    op.drop_index('ix_climb_version', table_name='climb')
    op.drop_table('climb')
    op.drop_index('ix_bicycle_route_membership_segment', table_name='bicycle_route_membership')
    op.drop_index('ix_bicycle_route_membership_ref', table_name='bicycle_route_membership')
    op.drop_table('bicycle_route_membership')
    op.drop_index('ix_waypoint_version', table_name='waypoint')
    op.drop_table('waypoint')
    op.drop_index('ix_validation_result_version', table_name='validation_result')
    op.drop_table('validation_result')
    op.drop_index('ix_stage_project', table_name='stage')
    op.drop_table('stage')
    op.drop_index('ix_source_discrepancy_route', table_name='source_discrepancy')
    op.drop_table('source_discrepancy')
    op.drop_index('ix_route_variant_comparison', table_name='route_variant')
    op.drop_table('route_variant')
    op.drop_index('ix_route_segment_version', table_name='route_segment')
    op.drop_table('route_segment')
    op.drop_table('route_score')
    op.drop_index('ix_poi_geom_category', table_name='point_of_interest')
    op.drop_table('point_of_interest')
    op.drop_index('ix_elevation_sample_version', table_name='elevation_sample')
    op.drop_table('elevation_sample')
    op.drop_index('ix_route_version_route', table_name='route_version')
    op.drop_table('route_version')
    op.drop_index('ix_route_source_version_source', table_name='route_source_version')
    op.drop_table('route_source_version')
    op.drop_index('ix_route_constraint_intent', table_name='route_constraint')
    op.drop_table('route_constraint')
    op.drop_index('ix_import_job_user', table_name='import_job')
    op.drop_table('import_job')
    op.drop_index('ix_avoid_area_owner', table_name='avoid_area')
    op.drop_table('avoid_area')
    op.drop_index('ix_route_intent_owner', table_name='route_intent')
    op.drop_table('route_intent')
    op.drop_index('ix_route_owner_visibility', table_name='route')
    op.drop_index('ix_route_origin_kind', table_name='route')
    op.drop_table('route')
    op.drop_index('ix_source_import_source_started', table_name='source_import')
    op.drop_table('source_import')
    op.drop_table('source_attribution')
    op.drop_index('ix_journey_project_owner', table_name='journey_project')
    op.drop_table('journey_project')
    op.drop_table('connected_account')
    op.drop_index('ix_route_source_connector_status', table_name='route_source')
    op.drop_table('route_source')
    op.drop_index('ix_app_user_organisation', table_name='app_user')
    op.drop_table('app_user')
    op.drop_table('source_licence')
    op.drop_table('organisation')
    # ### end Alembic commands ###

    # PostgreSQL keeps named ENUM types after their tables are dropped, so a
    # downgrade that omits this leaves them behind and the next upgrade fails
    # with "type ... already exists". Dropping them makes downgrade a true
    # inverse of upgrade, which is what the rollback procedure in
    # docs/operations.md depends on.
    for enum_name in (
        "bicycle_access",
        "bicycle_type",
        "connector_status",
        "cycle_lane_kind",
        "feasibility_verdict",
        "generalised_surface",
        "knowledge_status",
        "redistribution_permission",
        "road_class",
        "route_origin_kind",
        "route_visibility",
        "stage_balance_strategy",
        "surface_family",
    ):
        op.execute(sa.text(f'DROP TYPE IF EXISTS {enum_name}'))

